### ISSUE TITLE
removing client out of download function

### ISSUE THREAD

**Issue by mdenolle** [mdenolle/NoisePy#103]
Can we move 
# download parameters
client = Client("SCEDC")  #

out of S0A_download_ASDF_MPI.py ? 
Having the name of the data center as a string argument to ConfigParameters would be a lot better. They are generated by the FDSN routine web services: https://docs.obspy.org/tutorial/code_snippets/retrieving_data_from_datacenters.html
And users will know. it can be "IRIS" or "NCEDC" or "SCEDC", ...

**Comment by carlosgjs** [comment]
Fixed in #106
