### ISSUE TITLE
ERROR: Could not build wheels for mpi4py, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by CharlesH-Coding** [mdenolle/NoisePy#114]
Slight addition to the install instructions got rid of this error:

conda create -n noisepy python=3.8 pip
conda activate noisepy
conda install -c conda-forge openmpi
pip install noisepy-seis

# The pip install fails at mpi4py but you can install it with conda:
conda install mpi4py
pip install noisepy-seis # to wrap up the install

**Comment by carlosgjs** [comment]
MPI is no longer required, but support for MPI can be installed as an optional depedency:
```
pip install "noisepy-seis[mpi]"
```
