### ISSUE TITLE
setup.py broken

### ISSUE THREAD

**Issue by viktor76525** [mdenolle/NoisePy#12]
last parenthesis should be a bracket and then the parenthesis moved down.
```
    )
```
should become
```
   ]
)
```
at the bottom of setup.py

**Comment by viktor76525** [comment]
I'll just add one more `setup.py` issue instead of creating a new one.

The installed package is called `src` so you would have to `import src` to use NoisePy as an import. Files that should be used as scripts can be set using the `scripts` section.

**Comment by niyiyu** [comment]
Thanks for pointing out this syntax error. We've fixed this and would continue working on making the configuration/scripts easier to run.
