### ISSUE TITLE
check_read_speed.py not python

### ISSUE THREAD

**Issue by viktor76525** [mdenolle/NoisePy#13]
Just ran a quick test on the code with the black formatter.

> error: cannot format NoisePy/test/performace_check/check_read_speed.py: Cannot parse: 45:4:     %time read_data(sfile1,seg1,type1,tag1)

Not sure if these are meant to be comments using Matlab or FORTRAN syntax but because the for loop itself is not commented it wouldn't work even if replaced with the Python comment (`#`)

**Comment by chengxinjiang** [comment]
Thanks for your interests in looking at our test scripts. We do not attempt to ensure all scripts in the test folder work perfectly at the user's end. But for your reference, to run this read_speed test, you should use ipython and copy paste the script content there. The %time command is not a python function but ipython.
