### ISSUE TITLE
repeated use of the download function fails

### ISSUE THREAD

**Issue by mdenolle** [mdenolle/NoisePy#132]
Hello,

If we repeat the download functions, it fails saying:
`h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (file is already open for read-only)`

Does this mean that H5 files are still open after the download and cannot be overwritten?

**Comment by carlosgjs** [comment]
Repro: 
```
download(...)
....
cross_correlate(...)
...
download()
```
The issue is that the CCDataStore is indeed keeping the files open.
