### ISSUE TITLE
cross correlate not recomputed after removing CCF

### ISSUE THREAD

**Issue by niyiyu** [mdenolle/NoisePy#133]
Hi,

I am testing the get_started notebook in the tutorial. I download the data and computed the correlation. Later I removed the CCF folder, changed some parameters, and wanted to recompute the CCF. But it seems that I would have to restart the runtime so that cc_store won't mark them as done. A potential cause might be that cc_store does not close the h5 file even I delete them. However, it is still the case if instantiate another cc_store.

Restarting the run time could be time-consuming, e.g., on Colab, however necessary if someone wants to play with the parameters. Any thoughts on this?

**Comment by carlosgjs** [comment]
Likely the same underlying issue as https://github.com/mdenolle/NoisePy/issues/132, I'll take a look
