### ISSUE TITLE
python 3 requirement not working

### ISSUE THREAD

**Issue by viktor76525** [mdenolle/NoisePy#14]
There is no library called `python` which is specified as a requirement so it won't install with `pip`, a standard way to install Python packages.

The correct way to specify a required version of python is here:
[setup.py python-requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires)

**Comment by chengxinjiang** [comment]
The setup.py is indeed misleading. You can follow the README file here https://github.com/mdenolle/NoisePy for the detailed installation (for the dependent library rather than the package itself). The setup.py is not needed since our NoisePy package is scripts-based.

**Comment by viktor76525** [comment]
OK, but the sample scripts also do not work. I have forked it to try and fix them. Not only are the paths hardcoded absolute paths to your personal home directory but even when this is fixed, the parameters do not match from S0A to S0B to S1 etc...

**Comment by chengxinjiang** [comment]
I think it is really every developers' dream to design a package/code which applies for different purposes while it still does not require any changes/modifications/bug-fixes. With this in mind, I think it makes sense that you would always need to tweak others' code to fit your purpose. The NoisePy highlights the parameter sections in the beginning of every script, so the users themselves can make changes very easily to adopt to their own data/projects. Unfortunately, I do not know where your local data is, and where you want to put them, what format that is, what date of the noise data is, what stations are these data for etc, so PLEASE change it accordingly by yourself. Also, I would suggest you to really spend a bit time to read the notes in the package, each parameter is accompanied with an explanation. If you do, i bet you will find them really useful and you will probably have no such unfair comments any more.

**Comment by mdenolle** [comment]
Hi @viktor76525 , 
can you post the error messages and the scripts you are trying to run so that we can help debug? Thank you very much for your feedback and we'll clean up. Noisepy should not be run as a blackbox. We will make this more clear in the readme.

**Comment by viktor76525** [comment]
Thanks @mdenolle 

So far I've changed the hardcoded root path to something that will work out of the box
`rootpath = os.path.abspath("./NoisePy_example")`

uncommented https://github.com/mdenolle/NoisePy/blob/master/src/S1_fft_cc_MPI.py#L103 so that the `iii` variable won't go past end of array bounds.

restored original params as the ones available in repo (station download lat/lon bounding box, CI network) so that we can follow your tutorial (the station in the example is available by following the example). I think that even though the user is expected to change parameters it's very important that you can follow the tutorial straight away to get something working.
If I could just download the code, run steps S0A, S1, S2 and get the same figures as in your tutorial I would have a good idea of what is happening and be able to adapt the code from there.

There's a whole bunch of miscellaneous changes, I haven't been stuck on any 1 issue for too long.

The branch I'm working on is here:
https://github.com/ucgmsim/NoisePy/tree/fixes

**Comment by chengxinjiang** [comment]
Sorry @viktor76525 for my last comment, which is very emotional. I guess I was always assuming the comments are made from users' perspective, and forgot that GitHub is more a community for developers (a good lesson for me). All I was thinking at that time is, a user that wants to use others' code but is not even willing to change the rootpath in oder to adapt to his/her own data. I think you made very reasonable comments here that the sample scripts should work well to get the same results as those shown in the tutorials. Marine and I will carefully clear up the codes, particularly these sections related to your comments. Again, I apologize for my last (unfair) comment and thank you for looking at our NoisePy codes and making suggestions.

**Comment by viktor76525** [comment]
No worries @chengxinjiang, thanks for your response. Looking forward to trying again once you make updates to the codes. It will be nice functionality for the community.

**Comment by niyiyu** [comment]
The python version requirement in `setup.py` is now solved in commit 63a7c09. We are also moving hardcoded parameters into another file as enhancement #48. Thus, I am closing this issue. Thanks for all your discussion.
