### ISSUE TITLE
Validate that the inventories used match the timeframe of the cross correlation computation

### ISSUE THREAD

**Issue by carlosgjs** [mdenolle/NoisePy#143]
While debugging the scenario in the `get_started.ipynb` tutorial we uncovered some problems when filtering the StationXML inventory by time frame. This comes from the downloaded data from S0.

Here's one particular case:

```
# Information in the inventory:
Network CI: start_date:  UTCDateTime(2023, 4, 26, 20, 51)
Station AVM: start_date: UTCDateTime(2015, 5, 12, 16, 50)
Channel BHE: start_date: UTCDateTime(2010, 10, 28, 18, 0)

Cross correlation start_datetime= 2019-02-01T00:00:00+0000
```
It's strange that the Network has a later start date. From the records, this network was deployed at 1926.

This call is returning an empty inventory:
```
 inv.select(channel="bhe", time=obspy.UTCDateTime(ts.start_datetime))
```
But it works if we remove the `time` parameter.

**Comment by carlosgjs** [comment]
https://github.com/obspy/obspy/blob/d2981ba429eb084d439316d843b16e118f7b61aa/obspy/core/inventory/inventory.py#L650

**Comment by niyiyu** [comment]
Interesting. By checking through SCEDC's web service, it seems that the data center is giving a wrong network start date. https://service.scedc.caltech.edu/fdsnws/station/1/query?net=CI&sta=AVM&level=response&format=xml&includeavailability=false&nodata=404

network CI, station AVM, response level, and I can see in the XML that
```
...
<ModuleURI>
http://service.iris.edu/fdsnws/station/1/query?net=CI&sta=AVM&level=response&format=xml&includecomments=true&nodata=404
</ModuleURI>
<Created>2023-08-25T14:50:24.4361</Created>
<Network code="CI" startDate="1926-01-01T00:00:00.0000" restrictedStatus="open">
<Description>Southern California Seismic Network (SCSN)</Description>
...
```

However, the same query from IRIS shows the correct results. http://service.iris.edu/fdsnws/station/1/query?net=CI&sta=AVM&level=response&format=xml&includecomments=true&nodata=404
```
...
<ModuleURI>
http://service.iris.edu/fdsnws/station/1/query?net=CI&sta=AVM&level=response&format=xml&includecomments=true&nodata=404
</ModuleURI>
<Created>2023-08-25T14:49:24.3598</Created>
<Network code="CI" startDate="1926-01-01T00:00:00.0000" restrictedStatus="open">
<Description>Southern California Seismic Network (SCSN)</Description>
...
```

This could be a data center issue that persists until today (Aug 25, 2023). In contact with the SCEDC to investigate this issue.

**Comment by niyiyu** [comment]
Update:

SCEDC has corrected the metadata of CI network.
https://service.scedc.caltech.edu/fdsnws/station/1/query?net=CI&level=station&format=xml&includeavailability=false&nodata=404
```
...
<ModuleURI>
http://service.scedc.caltech.edu/fdsnws/station/1/query?net=CI&sta=AVM&level=resp
</ModuleURI>
<Created>2023-09-06T20:40:53</Created>
<Network code="CI" startDate="1900-01-01T00:00:00" endDate="3000-01-01T00:00:00">
<Description>Southern California Seismic Network</Description>
...
```
