### ISSUE TITLE
Download data via CLI

### ISSUE THREAD

**Issue by kuanfufeng** [mdenolle/NoisePy#144]
While downloading data through the CLI, we are having problems when querying data from IRIS. We have tested and successfully downloaded the same data through the Notebook but got no data massage via CLI. 

In the config.yml, the dates, stations, network code, etc. were changed and the client_url_key para was added:
`start_date: 2022-09-01 00:00:00
end_date: 2022-09-02 00:00:00
...
lamin: 22
lamax: 25
lomin: 119
lomax: 123
...
net_list: 'TW'
stations: 
YULB
TWGB
channels:
BHZ
client_url_key:
IRIS`

The error message:
`Traceback (most recent call last):
  File "~/miniconda/envs/noisepy/bin/noisepy", line 8, in <module>
    sys.exit(main.main_cli())
  ...
  File "~/miniconda/envs/noisepy/lib/python3.8/site-packages/obspy/clients/fdsn/client.py", line 1813, in raise_on_error
    raise FDSNNoDataException("No data available for request.",
obspy.clients.fdsn.header.FDSNNoDataException: No data available for request.
HTTP Status code: 204
Detailed response of server:`

But it works while calling download function at the Notebook (get_started.ipynb) as changing config parameters and
`download(raw_data_path, config, "IRIS")`.

**Comment by carlosgjs** [comment]
The problem was that the `client_url_key` was its own parameter, independent of the ConfigParameters so there was no way of passing it via the CLI or the config file.
