### ISSUE TITLE
Documentation for creating DataStore

### ISSUE THREAD

**Issue by mdenolle** [mdenolle/NoisePy#145]
We need to develop tutorials on how to create a data store given an archive or how to structure the data in order to match a specific data store. I think telling people to match the SCEDC data storage is reasonable. We should also have some tips on how to leverage the methods in the data stores.

**Comment by niyiyu** [comment]
See https://github.com/mdenolle/NoisePy/blob/master/tutorials/noisepy_datastore.ipynb for more documentation.
