### ISSUE TITLE
No data found in subdirectory (Sorry of interrupting)

### ISSUE THREAD

**Issue by SorawatSiangpipop** [mdenolle/NoisePy#17]
Again, sorry for interrupting, I'm quite new for the field and I'm interested in your codes.

In details, I lately was running 'S0B_to_ASDF' with my 30 days MSEED data named like 'TM.CMMT.BHZ.mseed' for 3 stations.
'station.cvs' info as
network	station	channel	latitude	longitude	elevation
TM	CMMT	BHZ	18.814363	98.945008	399.7

There is no data was found in the subdirectory
![image](https://user-images.githubusercontent.com/32880423/83922565-b91a2a00-a7aa-11ea-92a4-7ab1eee8aee5.png)

I was wondering if there might be specific required name or I need stationXML in some folder or I need to arrange station.csv info in some kind of pattern or any idea what I've done wrong?

Thank you in advance

**Comment by mdenolle** [comment]
Hello,

Can you ls into this specific directory? The scripts at this point have
hard coded absolute paths to folders that are *user specific* and that
*need to be changed*.
Cheers,
Marine
