### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Lukman-abdn19** [mdenolle/NoisePy#19]
After following all the installation steps in the documentation, the message below below paired while  tried to test if the installation was done properly.

(noisepy) ....MacBook-Pro:~ nnnnnn$ python S0_download_ASDF.py python: can't open file 'S0_download_ASDF.py': [Errno 2] No such file or directory

**Comment by Lukman-abdn19** [comment]
I am using Mac High Seira OS

**Comment by chengxinjiang** [comment]
Thanks for your interests in using NoisePy. Based on your error msgs, I think you are not running the command line of "python S0A_download_ASDF_MPI.py" from the folder where the scripts are located. Note that the NoisePy is purely scripts based, so they should be run in the same way when you run a python script of your own. Let me know how that helps.

**Comment by Lukman-abdn19** [comment]
Thanks for the reply and please can you describes the steps for me because I seem to be confuse here? I am using terminal but it only recognise python3 when in base. So when I run all the install commands it ok but gives me the above error message even after trying this "python S0A_download_ASDF_MPI.py".

**Comment by mdenolle** [comment]
Hi!
If you use python, you can use in the terminal "python code.py", if you use python3, then use "python2 code.py". I usually alias "python" for "python3" in my bashrc or bash_profile.

**Comment by Lukman-abdn19** [comment]
Hi,
I have this type of error, "ERROR: Could not build wheels for obspy which use PEP 517 and cannot be installed directly" what should I do please? Thanks

**Comment by Iskandarsyah17** [comment]
help. I got message that obspy and pyasdf packages are not available. but when pip install it, it shows "Requirement already satisfied". what should I do? please help

**Comment by nrich20** [comment]
I encountered the same issues when trying to run this module. It worked when I tried to Conda install the modules. Another issue that is when trying to run the module is that the file name has a typo in it. The actual file is named S0A_dowload_ASDF_MPI.py. It is missing the N in download.

**Comment by niyiyu** [comment]
The installation has been updated, and the file name has been corrected. Thanks for all of your discussion, and I am closing this issue.
