### ISSUE TITLE
rename core scripts

### ISSUE THREAD

**Issue by mdenolle** [mdenolle/NoisePy#193]
to avoid confusion when users/developers look at the code, i recommend that we change the naming:
- S0B_download_ASDF_MPI.py into `S0_parallel_download.py`
- S0B_to_ASDF.py should be renamed something like S0B_to_ASDF_2019.py or something like that that track the version.
- S1_fft_cc_MPI.py into S1_correlate_parallel.py
- S2_stacking.py stays as is.

**Comment by carlosgjs** [comment]
@mdenolle I'd be inclined to rename these to simpler names, e.g.:

download.py
correlate.py
stack.py

I feel like 'parallel' is an implementation detail. E.g. numpy modules are not named `_vectorized` even though most operations are. The step prefix is also not very "pydantic". As an example, ML workflows such as training a model also have an inherent sequence to them (e.g. compute features, train, evaluate) but frameworks such as PyTorch or sklearn don't  use sequence numbering in the module names. Plus people may not know coming in that `S` stands for step. The imports also become more intuitive:

```
from noisepy.seis.correlate import cross_correlate
``` 
vs
```
from noisepy.seis.S1_correlate_parallel import cross_correlate
```
WDYT?

**Comment by mdenolle** [comment]
I think that is good. I need to document well the transition from the 2020 version that is published, and it should be documented in a JBook.

**Comment by carlosgjs** [comment]
Done in #210
