### ISSUE TITLE
Question about dealing with local SAC data

### ISSUE THREAD

**Issue by promise-yy** [mdenolle/NoisePy#20]
When I used S0B subprogram to deal with local SAC data, I found that the content format of 'allfiles_time.txt' was difficult to set as required. According to the annotation in the program, it contains the path+name for all sac/mseed files and its start-end time , so I set the content as :
names,starttime,endtime
E:\eclipse-workspace\pycharm\NoisePy-master\noisepy_data\RAW_DATA\2018.365.JJ.NJ.BHZ.D.sac,2018-12-31T15:59:57.320000,2019-01-01T16:00:03.660000
E:\eclipse-workspace\pycharm\NoisePy-master\noisepy_data\RAW_DATA\2019.001.JJ.NJ.BHZ.D.sac,2019-01-01T15:59:59.870000,2019-01-02T16:00:01.220000
But it prompted error:
ValueError: could not convert string to float: '2018-12-31T15:59:57.320000'
Could u help me and give me a reference allfiles_time.txt?

**Comment by chengxinjiang** [comment]
Hi @promise-yy,

Thanks for your interests in using NoisePy. I notice that your question here is not well explained in our current documentation. For your further reference, the starttime and endtime should be in float format, which is defined as UTCDatetime in sec relative to 1970.01.01. You can find more details in the "make_timestamps" function in noise_module, for example, at L112-113. 

The current S0B is actually coded in a way that the script can write the "allfiles_time.txt" for you. To do that, you need to set "allfiles_path" well for all the absolute path of your data, and no "allfiles_time.txt" is available at your "rootpath". Depending on the how organized your local data is, you can set "messydata" at L62 in S0B to be "True", so the code will try to scan everything in your provided absolute path.

Let me know how it works with the above modifications.

Cheers,
Chengxin
