### ISSUE TITLE
Problem with Stacking

### ISSUE THREAD

**Issue by boyoforex** [mdenolle/NoisePy#21]
Hi, thanks for sharing your excellent code. I have successfully followed the entire work-flow without issues on a small dataset but now I am having this issue with a much larger dataset. The error message is quite informative but unfortunately i am unable to resolve it on time. If you have come across this error, I will be grateful for some suggestions.

`Traceback (most recent call last):
  File "S2_stacking.py", line 207, in <module>
    cc_array[iseg] = tdata[ii]
ValueError: could not broadcast input array from shape (1799) into shape (12001)`

Thanks

**Comment by mdenolle** [comment]
This is an old issue. The new noisepy version may no longer be appropriately related to this issue. Recommend tracking array dimensions to solve this.
