### ISSUE TITLE
Testing scripts in NoisePy Read the Docs not working

### ISSUE THREAD

**Issue by suhsane** [mdenolle/NoisePy#22]
Hello,

I'm new to Python and have minimal background in programming in general, so apologies if this question should be obvious. I have been running into a number of issues during the installation of NoisePy, and am using Windows 10. I believe one of these issues is attributed to the name of the scripts being changed in NoisePy.

After cloning the github repository, the NoisePy files located in the \src folder, are named as follows:

S0A_dowload_ASDF_MPI.py
S1_fft_cc_MPI.py
S2_stacking.py

Of these three files, only one of them (S2_stacking.py) matches the naming used in the tutorial --> testing documentation. Please let me know if this is an error or if there is another location where the "testing" files are located, and how to find them. 

Thanks in advance.
![noisepy testing](https://user-images.githubusercontent.com/6075834/97901711-c4da3000-1cf9-11eb-9c88-8a48675f9543.JPG)

**Comment by chengxinjiang** [comment]
apologies for this very late reply. Thanks for pointing out this mistake. The names in the docs should be consistent with those in the src folder, and i have corrected the names in the docs. Let me know if you see any further problems.

**Comment by suhsane** [comment]
Thank you for updating!
