### ISSUE TITLE
Format of file allfiles_time.txt

### ISSUE THREAD

**Issue by nghia1991ad** [mdenolle/NoisePy#23]
Hi, thanks for the nice program, can I ask for some help? In tutorial S0B, the program needs a file named "allfiles_time.txt" with comment "# file containing the path+name for all sac/mseed files and its start-end time". Could you give an example of the file?

**Comment by nghia1991ad** [comment]
I have done it. The format should be:
names,starttime,endtime
file1,1567728000.02,1567814400.02
file2,1566864000.02,1566950400.02
file3,1561900528.42,1561900812.37

with the time is the relative time to UTCDateTime(1970,1,1).

**Comment by sedaist** [comment]
First of all, I'm sorry I'm taking your time. If possible, can I ask something?
When I edit the content  of the allfiles_time.txt file as you wrote in the github forum, start time and end time do not cause any problems,but it gives a KeyError: 'names' error.
I wonder how to write the file name as an example. Can you help me?
in the form of my data file name GA.c0ATU..SHZ.2017.277.sac thank you in advance
 @nghia1991ad
