### ISSUE TITLE
Issue with auto-correlation of three component data

### ISSUE THREAD

**Issue by ChetGoerzen** [mdenolle/NoisePy#26]
Dear NoisePy authors,

Thank you for making the NoisePy code available, I greatly appreciate it. I have been working to calculate the auto-correlation functions of three component data for the purposes of temporal monitoring. While doing this I noticed an issue with the calculation of auto-correlation functions with three component data.using the S1_fft_cc_MPI.py script It seems that the wrong data is being selected for the calculation. In my case, there will be 6 auto-correlation functions for the station I desire, and a spurious 3 correlations will be produced between the desired station, and the next station in the station list. This is because the range of receiver stations used in the auto-correlation calculation is defined as the index of the source station + the number of components. In this case, the auto-correlations for the first channel of the source will be calculated correctly. However, because the index of the second channel of the source is one higher than the index of the first source channel, only two auto-correlations will be correctly calculated for the second channel, and the cross-correlation will instead be calculated between the second source channel and the first channel of the next receiver in the station list after the desired receiver. I managed to fix this by adjusting the range of indexes used for the receiver, such that all nine auto-correlation components are correctly calculated.

Thanks,

Chet

**Comment by chengxinjiang** [comment]
Dear Chet,

Many thanks for your interests of using NoisePy as well as your post here. It is indeed an issue in the current noisePy. Just for your notice, the index for "xcor-only" is also problematic and replacing the original L304-306 with the snippet code below should help fix both problems.

        istart=iiS;iend=iii
        if acorr_only:
            if ncomp==1:
                iend=np.minimum(iiS+ncomp,iii)
            else:
                if (channel[iiS][-1]=='Z'):
                    iend=np.minimum(iiS+1,iii)
                elif (channel[iiS][-1]=='N'):
                    iend=np.minimum(iiS+2,iii)
                else:
                    iend=np.minimum(iiS+ncomp,iii)
            
        if xcorr_only:
            if ncomp==1:
                istart=np.minimum(iiS+ncomp,iii)
            else:
                if (channel[iiS][-1]=='Z'):
                    istart=np.minimum(iiS+1,iii)
                elif (channel[iiS][-1]=='N'):
                    istart=np.minimum(iiS+2,iii)
                else:
                    istart=np.minimum(iiS+ncomp,iii)

We are going to incorporate this change into our next version of release of NoisePy. 

Cheers,
Chengxin
