### ISSUE TITLE
SAC Files

### ISSUE THREAD

**Issue by zee1978** [mdenolle/NoisePy#28]
Hi
I am a beginner.
I want to use this code to read my sac files. Here attached. 
I need to correlate and stack the data and get dispersion curves.
I need your kind and immediate help.
[TEST.zip](https://github.com/mdenolle/NoisePy/files/7168217/TEST.zip)
Regards

**Comment by mdenolle** [comment]
Hello! Thank you for your interest. With the new refactoring of noisepy, I recommend that you revisit your work with the new package. It will also be quite useful to provide more guided instruction on where things bug and especially asks specific questions.
