### ISSUE TITLE
S0B error

### ISSUE THREAD

**Issue by jollyjokers** [mdenolle/NoisePy#31]
Dear Author :
       I appreciate reading your paper. And I always have some SAC files to process that I want to use NoisePy.But in the first step, I met some errors in the S0B. I read the documentation and still don't know how to prepare the original data and run it. So could you please make an example for the S0B. Thanks very much.

**Comment by chengxinjiang** [comment]
@jollyjokers thank you for your interest of using NoisePy. We recently received quite many interests in using S0B, and I am working on an example to better demonstrate the S0B functionality. Will keep you posted once it is available.

**Comment by mdenolle** [comment]
Given the refactoring of noisepy, i will close this comment. And i hope that @jollyjokers eventually succeeded at running cross correlations!
