### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by da0bi** [mdenolle/NoisePy#32]
1.)
SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' on line 26
...closing bracket ']' of the classifiers is missing

2.)
install_requires=
[..., python>=3.0, ...]
can't be used to check if python version requirement is fullfilled - an error will be raised.
There is a special python version requirement query with following syntax:
python_requires='>=3'

**Comment by chengxinjiang** [comment]
Many thanks for your comments. I have incorporated them into a local branch and will be merged to the main later.
