### ISSUE TITLE
error in S0B_to_ASDF

### ISSUE THREAD

**Issue by Wz-hq** [mdenolle/NoisePy#33]
Dear NoisePy authors,
Thank you for sharing the code, I greatly appreciate it. I want to use code (S0B_to_ASDF.py) to convert sac files to adsf files ,When I run the code, the error appears: Can you tell me where the problem is?
Thanks,
error:
runfile('K:/rj/NoisePy/src/example2.py', wdir='K:/rj/NoisePy/src', post_mortem=True)
Traceback (most recent call last):

  File "K:\rj\NoisePy\src\example2.py", line 205, in <module>
    inv1   = noise_module.stats2inv(source[0].stats,prepro_para,locs=locs)

  File "K:\rj\NoisePy\src\noise_module.py", line 365, in stats2inv
    cha.response = response

UnboundLocalError: local variable 'cha' referenced before assignment

****************************************
Entering post mortem debugging...
****************************************
> k:\rj\noisepy\src\noise_module.py(365)stats2inv()
    363     # Now tie it all together.
    364     #cha.response = response
--> 365     cha.response = response
    366     sta.channels.append(cha)

**Comment by niyiyu** [comment]
Hi, I am closing this issue given there has been changes in the `stats2inv` function. Please feel free to reopen this if you are still experiencing the same issue with the latest code and we are happy to quickly review it.
