### ISSUE TITLE
Error: Testing NoisePy

### ISSUE THREAD

**Issue by zee1978** [mdenolle/NoisePy#36]
Respected Professor
I want to work with ambient noise using NoisePy. During my installation, I have problem as

zafar@zafar-OptiPlex-5050:~$ python S0A_download_ASDF.py
Traceback (most recent call last):
  File "S0A_download_ASDF.py", line 12, in <module>
    import noise_module
ModuleNotFoundError: No module named 'noise_module'

**### zafar@zafar-OptiPlex-5050:~$ python S0A_download_ASDF_MPI.py
python: can't open file 'S0A_download_ASDF_MPI.py': [Errno 2] No such file or directory**

Can you please guide how to resolve the issues.

Also

**Comment by nrich20** [comment]
The part of the problem is that there is a typo in the name of the file. It is named S0A_dowload_ASDF_MPI.py. The file name is missing an N in the word download.

**Comment by niyiyu** [comment]
Thanks @nrich20 pointing this out! I renamed the script in commit 812cfa0.
