### ISSUE TITLE
Moving average function

### ISSUE THREAD

**Issue by lermert** [mdenolle/NoisePy#37]
Regarding the update of the moving average function recently performed by Natasha: After looking through the code of moving_ave again, we realized that the original function worked fine as long as N < len(A) (certainly a reasonable scenario). Therefore, if the original function was faster, it could be restored by adding a check that N is shorter than A to ensure that the function fails well rather than producing some hard-to-interpret error, e.g. starting 
`def moving_ave(A, N):
    assert A.shape[-1] > N, "The smoothing length N must be shorter than the array."`

or something along those lines.
If the new function is as fast as the old one, this is not needed.

**Comment by nrich20** [comment]
When trying to run the S1 function, I am getting an error message in the moving average function. The message states: 'TypeError: np_convolve() got an unexpected keyword argument 'mode' '

**Comment by chengxinjiang** [comment]
@lermert, apologize for the very late reply. You are right that the new function you and Natasha coded for moving average is way faster compared to the original function, with an average improvement of speed of about 100 times if the size of A is within 1E7. This means more than 1 daily continuous data even for a sampling rate of 100 Hz. 

Below is a snippet of script for testing. 

`
import time
import numpy as np
import scipy
from numba import jit
import matplotlib.pyplot as plt

def moving_ave1(A,N):
    '''
    Alternative function for moving average for an array.
    PARAMETERS:
    ---------------------
    A: 1-D array of data to be smoothed
    N: integer, it defines the full!! window length to smooth
    RETURNS:
    ---------------------
    B: 1-D array with smoothed data
    '''
    # defines an array with N extra samples at either side
    temp = np.zeros(len(A) + 2 * N)
    # set the central portion of the array to A
    temp[N: -N] = A
    # leading samples: equal to first sample of actual array
    temp[0: N] = temp[N]
    # trailing samples: Equal to last sample of actual array
    temp[-N:] = temp[-N-1]
    # convolve with a boxcar and normalize, and use only central portion of the result
    # with length equal to the original array, discarding the added leading and trailing samples
    B = np.convolve(temp, np.ones(N)/N, mode='same')[N: -N]
    return(B)

@jit(nopython = True)
def moving_ave2(A,N):
    '''
    this Numba compiled function does running smooth average for an array.
    PARAMETERS:
    ---------------------
    A: 1-D array of data to be smoothed
    N: integer, it defines the half window length to smooth

    RETURNS:
    ---------------------
    B: 1-D array with smoothed data
    '''
    A = np.concatenate((A[:N],A,A[-N:]),axis=0)
    B = np.zeros(A.shape,A.dtype)

    tmp=0.
    for pos in range(N,A.size-N):
        # do summing only once
        if pos==N:
            for i in range(-N,N+1):
                tmp+=A[pos+i]
        else:
            tmp=tmp-A[pos-N-1]+A[pos+N]
        B[pos]=tmp/(2*N+1)
        if B[pos]==0:
            B[pos]=1
    return B[N:-N]


#######################
#### MAIN FUNCTION ####
#######################
M,N = 1000000,30
tdata = np.random.rand(M)
t0=time.time()
tdata1 = moving_ave1(tdata,N)
t1=time.time()
tdata2 = moving_ave2(tdata,N)
t2=time.time()
print('t1=%5.4f,t2=%5.4f'%(t1-t0,t2-t1))
`

**Comment by chengxinjiang** [comment]
> np_convolve()

looks like this should be np.convolve().

**Comment by chengxinjiang** [comment]
@lermert , any ideas on why the follow-up errors by @nrich20 occur? It seems that issue #46 is reporting the exact problem. I have not been able to reproduce this error yet.
