### ISSUE TITLE
saving parameters into yml / CSV file

### ISSUE THREAD

**Issue by mdenolle** [mdenolle/NoisePy#48]
we should save the input parameters into a separate "config.ym" file that gets read at each step.
We should save the parameters as a data frame and into a CSV file.
we should remove the checkpoints that are saved into single files and save them into a separate CSV file that can track the progress to start again from that step, but only in a single csv file.

**Comment by carlosgjs** [comment]
Taking a look at this ...

**Comment by niyiyu** [comment]
This has been implemented through the `load_yaml` and `save_yaml` function in `ConfigParameters`. See https://github.com/mdenolle/NoisePy/blob/948d95f68d8120f23866c6442b502b4ae7e271af/src/noisepy/seis/datatypes.py#L216-L227
